Add BMP3xx and BMA423 drivers
mcauser/awesome-micropython pull request #159
Opened 2024-07-22 01:05 UTC by mattytrentini

Add an accelerometer and pressure sensor driver. 

Both were listed in this MicroPython discussion: [Implementing an IMU/accelerometer/gyro driver? Use the FIFO!](https://github.com/orgs/micropython/discussions/15512)

I've marked both drivers with "⏩" to indicate that the driver supports FIFO access. That was [suggested in that discussion](https://github.com/orgs/micropython/discussions/15512#discussioncomment-10106077) by @Josverl and I think it's a good idea to try out. Would be good to review other drivers and add the same badge where appropriate.

2024-07-22 02:13 UTC, mattytrentini commented
(I also took the opportunity to fix the broken link to the _Getting Started..._ book. The second version was released and the original link appears to have been removed.)

2024-07-24 13:42 UTC, andypiper requested changes

2024-07-24 13:42 UTC, andypiper commented on readme.md
> +* [bma423-pure-mp](https://github.com/antirez/bma423-pure-mp) - MicroPython Drive for the Bosch 423 accelerometer. Includes FIFO support. ⏩
nitpick -> Driver not Drive

2024-07-25 07:21 UTC, mattytrentini commented on readme.md
> +* [bma423-pure-mp](https://github.com/antirez/bma423-pure-mp) - MicroPython Drive for the Bosch 423 accelerometer. Includes FIFO support. ⏩
Thanks @andypiper! Fixed.

2024-07-26 00:58 UTC, mcauser approved these changes

2024-07-26 00:59 UTC, merged

2024-07-26 01:00 UTC, mcauser commented
Thanks guys!

2024-07-26 01:04 UTC, mcauser commented
Maybe we should add an emoji for mip installable 🤔

2024-07-28 20:48 UTC, Josverl commented
It's always hard to see how the icons look across platforms 
But the suitcase/package on the conveyor perhaps ?
🛄